### ISSUE TITLE
isSinglePage mode is missing last page

### ISSUE THREAD

**Issue by jrossgowan-pulsemining** [surveyjs/surveyjs#1009]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

When ``isSinglePage = true``, the elements from all pages _except_ the last page are shown. This seems to be a regression from surveyjs 1.0.1 to 1.0.2.

### What is the expected behavior?

The elements from all pages should be shown, including the last page.

### How would you reproduce the current behavior (if this is a bug)?

- Create a survey with more than one page
- Set ``isSinglePage = true``

#### Provide the test code and the tested page URL (if applicable)

https://plnkr.co/edit/4lu4K8FA0pOeDcPhWcW8?p=preview

### Specify your

* browser: Chrome, Firefox
* browser version: Chrome 66.0.3359.33 beta, Firefox 60.0b4
* surveyjs platform: jQuery
* surveyjs version: 1.0.2-1.0.14

**Comment by andrewtelnov** [comment]
@jrossgowan-pulsemining I have recreated the issue in the Unit Test and fixed it.
The bug was here from the beginning, but in knockout version. We are building jQuery version based on knockout version since v1.0.2 (as I remember). Before we were using react version and injected preact version. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Yes, the update will be likely released on this week.

**Comment by jrossgowan-pulsemining** [comment]
Thanks for the quick fix.
