### ISSUE TITLE
Show errors on changing question value (optional)

### ISSUE THREAD

**Issue by nicklas669** [surveyjs/surveyjs#1011]
Hello. I have an issue that I hope you can help out with.

### Are you requesting a feature, reporting a bug or ask a question?
Bug/question

### What is the current behavior?
If I have a field that is invalid, i.e. it has an validation error on it, and I change the input text to something that I know is valid and then move the mouse to the Submit button without first clicking outside the given field, tabbing out or somehow lose focus of the field, OnValueChanged event is triggered but OnComplete is not.

Below are a series of images in which I try to explain the issue:

![validation1](https://user-images.githubusercontent.com/4216390/37650743-1911d2b6-2c36-11e8-9c3e-9738dee78fe5.PNG)

![validation2](https://user-images.githubusercontent.com/4216390/37650753-1c24ad02-2c36-11e8-8ed1-b2fe2314e4a4.PNG)

![validation3](https://user-images.githubusercontent.com/4216390/37650757-1e18684c-2c36-11e8-9efd-351687b2441f.PNG)

Not sure if necessary but below is the code we use for the two events:
```
container.on('KC.Web.Survey.OnValueChanged', function (event, sender, eventOptions) {
                        var questionHasErrors = eventOptions.question.hasErrors(true); // Check if question has errors and update UI accordingly

                        if (!questionHasErrors) {
                            // Save draft progress on value changed
                            var data = {
                                FormId: options.Form.Container.attr('data-id'),
                                SerializedInput: JSON.stringify(JS.Util.ReplaceIllegalCharacters(sender.data))
                            };
                            JS.Service.Post('External/Complaint/PersistFormInput', data);
                        }
                        //navigation(sender);
                    });

container.on('KC.Web.Survey.OnComplete', function (event, sender) {
                        var data = {
                            FormId: options.Form.Container.attr('data-id'),
                            SerializedInput: JSON.stringify(JS.Util.ReplaceIllegalCharacters(sender.data))
                        };

                        JS.Service.Post('External/Complaint/SubmitForm', data, function (response) {
                            JS.Global.HandleUrlResponse(response);
                        });
                    });
```

### What is the expected behavior?
If I correct an invalid field and press the "Submit" button, without first triggering a OnValueChanged by changing focus out of the given field, I expect that the OnComplete event is triggered?

Kind regards,
Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 Unfortunately I could not reproduce this behavior so far. Could you please help us to reproduce it?
Here is the [plunker example](https://plnkr.co/edit/DZ60j6haFtkHiX75DmOb?p=preview)

Thank you,
Andrew

**Comment by nicklas669** [comment]
@andrewtelnov I believe I have recreated the issue. Look at the [plunker here](https://plnkr.co/edit/uxD1uq7evjlvOowHIa8z?p=preview). With the console open, type in 123 in the field and press Submit/Complete. One onValueChanged is printed and the error message "Please enter value 1000 or bigger" is correctly shown. Now add another digit, eg. 4, so the input says 1234. Now click the Complete button again. Two onValueChanged are printed and the error message correctly disappears. You now have to click Complete a second time to post the survey.

**Comment by andrewtelnov** [comment]
@nicklas669 Aha, I got it.
Let's look at the problem from a different angle. I believe you are doing it, because you want to show the error immediately and not only on page next/on complete, am I right?
If yes, lets add this functionality into the library, it is a valid scenario, IMHO.

Thank you,
Andrew

**Comment by nicklas669** [comment]
@andrewtelnov Yes that is our scenario. We need to not show any errors on initial survey load, show errors whenever a field changes, show errors on clicking next/complete and if there are no errors when clicking next/complete, the survey should not stay on the current page as described in this issue.

Thanks, Nicklas

**Comment by andrewtelnov** [comment]
@nicklas669 I will try to implement it in several days. It should not take a lot of time. The scenario makes a perfect sense to me.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@nicklas669 From the next minor version, you will be able to use the following code:
`survey.checkErrorsMode = "onValueChanged";`

Unfortunately, it doesn't fix the issue you are mention and what is more sad, I am afraid there is no way to fix it. I have spent couple hours trying to understand what's going on, untill I have ended up with the following [example](https://plnkr.co/edit/7vWG14y2JFp4tQnntn3t?p=preview). 
You may see this example has nothing to do with surveyjs or any javascript framework. It is pure javascript and html.
When you are entering more then 3 letters into input and click on the button, the div on top is hidden and the button onclick, simply is not fired.
Same happens in our library, next page or survey complete buttons click simply are not fired ;-)

Probably it is the expected behavior, I have checked several browsers. 

Thank you,
Andrew

**Comment by nicklas669** [comment]
Thanks for the feedback @andrewtelnov !

**Comment by mstoecke** [comment]
@andrewtelnov What if you use oninput event instead of onchange? It would trigger immediately after changing the input value. Wouldn't that help to solve the problem?

**Comment by tsv2013** [comment]
@mstoecke It was discussed in this thread - https://github.com/surveyjs/surveyjs/issues/1062
Here is the sample of the "validation on change" - https://plnkr.co/edit/ZNJ6TfOvHxLsquIXfmpY?p=preview
