### ISSUE TITLE
Add clearIncorrectValue(s) functions into survey/page/panel/question objects (Radiogroup with defaultValue not in choices)

### ISSUE THREAD

**Issue by mdickin** [surveyjs/surveyjs#1016]
### Are you requesting a feature, reporting a bug or ask a question?
Reporting a bug

### What is the current behavior?
If a radiogroup question is required, has a non-empty default value, and has a set of choices that _does not_ contain the default value, the required validation does not fire. The page can be submitted without choosing a radio button.

https://plnkr.co/edit/XdYSZuf3Wn0Nwtb8JYlE?p=preview

### What is the expected behavior?
I would expect the user to have to choose from one of the provided radio buttons.

Our use case involves users revisiting previous saved data, so if we were to change the options in a radio group, we would want them to have to choose from the new options.

### How would you reproduce the current behavior (if this is a bug)?
https://plnkr.co/edit/XdYSZuf3Wn0Nwtb8JYlE?p=preview

### Specify your

* browser: Chrome
* browser version: 64.0.3282.186
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.14

**Comment by andrewtelnov** [comment]
@mdickin How do you get this defaultValue in the first place? What is the scenario?

defaultValue simply does question.value = defaultValue; there is no any checks here and it should not, because it comes from developers and not UI.

If we start to check if the value exists in the choices, it would definately breaks some existing surveys.
Some people use survey.setValue and then set choices programmatically or using restfull api to get choices from a server.

Unfortunately we can't change it without breaking existing surveys.

We may add a function, that will go through all questions and clearValue if it is not correct. You will have to call it manually on survey loading. What do you think?

Thank you,
Andrew

**Comment by mdickin** [comment]
Ahh, I was afraid that it would break existing surveys. Would it be possible to add a flag for "limit value to the list of choices"?

As a workaround, I used `onValidateQuestion` to check radiogroup answers. Here's a plunker for it:

https://plnkr.co/edit/awOcCIJ0cNX27YMAcsEY?p=preview

**Comment by mdickin** [comment]
To answer your initial question, we are using SurveyJS on our account creation product. It walks the user through a handful of pages (most of which use your library for generating the questions) and stores the data. The user can navigate back to previous pages, sometimes days or weeks later. Thus, if we change the options in a question, we would want the user to have to choose from the new options.

**Comment by andrewtelnov** [comment]
@mdickin I believe if we add function `survey.clearIncorrectValues();`, it will clear all incorrect values in question, it would perfectly solve your problem and definately can be used by others.
And yes, clearIncorrectValue(s) we will add on Page/Panel/Question levels as well.
What do you think?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@mdickin You may call `survey.clearIncorrectValues();` after creating the survey model from the next minor release. It will do what you need.

Thank you,
Andrew
