### ISSUE TITLE
Add ability to hide the matrix dynamic/dropdown header

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1026]
Some surveys require to hide the matrix dynamic/dropdown table header.
There should be a property showHeader : boolean, true by default.

**Comment by andrewtelnov** [comment]
Implemented:
  /**
   * Set this property to false, to hide table header. The default value is true.
   */
  public get showHeader(): boolean;

**Comment by Buffalonian** [comment]
Does showHeader work off this type of setting?

questions : [
... 
showHeader = false;
...
]

I'm not setting a title on the question, and the default functionality is to show the name: value ... I don't want this, because I use font-awesome stars and have to inject html into the question format in the element above it to get the functionality I want.

Seems lame to be a default, but I get it. However, if this works ... great.

**Comment by Buffalonian** [comment]
Ya, I can agree with this. If you make it a GLOBAL, then the entire surveyJS JSON gets affected by it.

**Comment by andrewtelnov** [comment]
@Buffalonian I guess, you want just to hide the question title, then `question.titleLocation: hidden` is what you are looking for.

Thank you,
Andrew

**Comment by Buffalonian** [comment]
Yup! I found it in the code updates. Was tinkering with it on multiple elements, then realized where it was and what it was doing.

Before I was doing the titleLocation: hidden, I was using the css :empty but because the tags all have hidden comments in them for the switches that are used in JS, it doesn't take.

Either way, got through it and we did our push to production!!!! Thanks for such a fast reply, either way. Shows me how awesome SurveyJS and its community are.
