### ISSUE TITLE
Carry over survey questions for next session

### ISSUE THREAD

**Issue by ashygk** [surveyjs/surveyjs#1059]
### Are you requesting a feature, reporting a bug or ask a question?

Question

### What is the current behavior?

Survey questions appears as is.

### What is the expected behavior?

We are carrying over few answered survey questions for users next session by configuring the question names in a config file and the follow up questions, being configures as child questions.
Carry over doesn't happen for questions withing dynamic panels and questions within panels.

#### Provide the test code and the tested page URL (if applicable)
Below is my sample config file 

"SurveyName": [
      {
        "questionName": "IsYourCarInGoodCondition",
        "carryOverOnValue": "Yes",
        "carryOverChildQuestions": [
          "YearOwned",
          "HowManySeater",
          "SizeOfCar"
        ]
      },
      {
        "questionName": "blahblahblah",
        "carryOverOnValue": "*",
        "carryOverChildQuestions": ["xyzabc"]
      }
    ],

where carryoverchild questions are follow up questions

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): angular 5
* surveyjs version: 1.0.0

**Comment by andrewtelnov** [comment]
@ashygk Please review the following [example](https://surveyjs.io/Examples/Library/?id=real-patient-history). It save/restore survey resutlts in the local storage. There several dynamics panels and it works perfectly.

Thank you,
Andrew

**Comment by ashygk** [comment]
Is there a possibility to just save few questions? Based on our requirements, we do not all the questions to be saved.

Also, synchronization is of concern here, as our form is being used by number of users and I would like my application to realize there are some changes and have the latest answers.

**Comment by andrewtelnov** [comment]
@ashygk Sure, it is up to you. You may create your own json as:
```
var savedData = {};
for(var i = 0; i < allNeededQuestionNames.length; i ++) {
  var key = allNeededQuestionNames[i];
  savedData[key] = survey.getValue(key);
}
```
and then reverse:
```
foreach(key in savedData) {
  survey.setValue(key, savedData[key]);
}
```
Something like that.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ashygk The  synchronization part - local storage would not work for you. You will have to write a service/push notifications. I would do it in the following way:
On [survey.onValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onValueChanged) event, send a callback to the server that particular user has changed this question into newValue at this time. Then the server should send all other clients a push notification, that a question at particular time has been changed.
If another user (client) doesn't change the value since that time then update the question value.

You may need to handle matrix differently, using [survey.onMatrixCellValueChanged](https://surveyjs.io/Documentation/Library/?id=surveymodel#onMatrixCellValueChanged) event.

Anyway, there are a lot of coding and it has little to do with our library :-)

Thank you,
Andrew
