### ISSUE TITLE
In Panel Dynamic, the value instead of the text shows up when answer is used in labels and titles

### ISSUE THREAD

**Issue by ajien** [surveyjs/surveyjs#1212]
### Are you requesting a feature, reporting a bug or asking a question?

A bug

### What is the current behavior?

When using dynamic panel, the value instead of the text shows up when answer is used in label

### What is the expected behavior?

The text should be used instead of the value when using answers in titles and labels

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): ReactJS
* surveyjs version: 1.0.13

**Comment by andrewtelnov** [comment]
@ajien Could you please check the current version? 1.0.30? 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@ajien I have made an example: https://plnkr.co/edit/C3WPStMIsKj8VkaEWoQz?p=preview
```
"choices": [
    {value: "f", text: "father"},
    {value: "m", text: "mother"},
    {value: "sis", text: "sister"},
    {value: "s", text: "son"},
    {value: "d", text: "dauhter"}
]
```
It works as expected.

Thank you,
Andrew

**Comment by ajien** [comment]
Hi, Andrew. Here's my own example
<https://plnkr.co/edit/5bBeyx20oFdMssWGKWAc?p=preview> showing the issue. I
wonder why it works in jQuery example that you gave but not in my example.

**Comment by andrewtelnov** [comment]
@ajien The magic in showing display text instead of value, happens when surveyjs can find the question and see if there is a choices property, where it can get text by value. In this case, it can show text instead of value.
In your case, you are setting the community value into your second panel dynamic in the code. SurveyJS could not find any related question in the second panel.
To deal with it, you may make invisible radiogroup "community" with the same choices as in the first panel (you may even assign choices property in the code). In this case SurveyJS should find this question and do a magic.

PS: Why do you need the first panel as a  paneldynamic? It could be a normal panel. You do not need to add/remove panels here.

Thank you,
Andrew

**Comment by ajien** [comment]
Thanks, @Andrew. Adding the hidden questions fixed my problem. I tried
doing your suggestion about changing the first panel to a regular panel but
it does not seem to work. I'll keep it as a paneldynamic for now until I
figure out a way to make it work.
