### ISSUE TITLE
question values not cleared when parent panel is hidden

### ISSUE THREAD

**Issue by moldoe** [surveyjs/surveyjs#1343]
I'm using "clearInvisibleValues": "onHidden" to clear question values which are hidden.
When the questions are part of a panel that is being hidden the values are not cleared.
I'm not sure if this intended behavior but personally I was expecting that, when a question(s) becomes invisible either by hiding it directly or by hiding it's parent container(panel), the value of the question(s) would be cleared.

Please look at the following example:
https://plnkr.co/edit/nTci9V?p=preview

When I use the sequence Hide followed by Show from the first dropdown I would expect that both 'Text 2' and 'Text 3' would be cleared.

On a second thought, maybe the page and panel should also have a "clearInvisibleValues" config to allow developers to control the behavior.

Thanks,

Daniel

**Comment by andrewtelnov** [comment]
@moldoe I wanted to add a unit test and fix the issue. However, I am not sure that it would be the right implementation.
We may clean all values in questions on hiding their containers. It looks logical for your example, However, if it is a complex form with many nested panels, should we clear all values on hiding the root panel?
What about page? Should we clear all values on the page, if the page is hidden? I am not sure it would be expected behavior. I would love to hear opinion of other users.
We may introduce an additional option. On setting this new option, we will clear questions values on hiding their container. What do you think?

Thank you,
Andrew

**Comment by moldoe** [comment]
You're right. For pages this doesn't make sense as you wouldn't want to clear the values when you go to next page.
But for panels it may be useful depending on each specific scenario. So having some configuration to control this behavior on a per panel basis may be the right implementation. The config could have values like:  'do not clear', 'this panel only', 'nested panels'. And should probably work together with the overall Survey config for "clearInvisibleValues".

**Comment by moldoe** [comment]
In the mean time for my scenario I did this:

`
survey.onPanelVisibleChanged.add(function(survey, options){
            if (!options.visible) {
                var questions = options.panel.questions;
                for (var i = 0; i < questions.length; i++) {
                    var question = questions[i];
                    question.value = undefined;
                }
            }
        });
`

**Comment by andrewtelnov** [comment]
@moldoe I think that your solution is working perfectly.
I would only change the code from setting value to underfined to `questions[i].clearValue(); `
It is a better way to do it.

Thank you,
Andrew

**Comment by moldoe** [comment]
Thanks!
