### ISSUE TITLE
Parameters for choicesByUrl should be encoded

### ISSUE THREAD

**Issue by andrewtelnov** [surveyjs/surveyjs#1473]
choicesByUrl doesn't work correctly if the parameter value has '&' character.
For example:
choicesByUrl: "TheServerPath/parameter={your_parameter}" and your_parameter equals to "R&D".
The library sends the request as: "TheServerPath/parameter=R&D"
instead of encoding string as: "TheServerPath/parameter=R%26D".

**Comment by andrewtelnov** [comment]
To turn off parameter encoding set this static property: `Survey.ChoicesRestfull.EncodeParameters = false;`.

Thank you,
Andrew

**Comment by masciugo** [comment]
Hi @andrewtelnov, I would like to keep Survey.ChoicesRestfull.EncodeParameters set to true but the problem is that this causes the _ TheServerPath_ to be encoded too and added to the original one. For example in my case the following url:

`http://localhost:3000/people/P_BDNKIFFUNK/samples/visible_to_collectors/54`

is encoded to:
 `http://localhost:3000/projects/1/participants/P_BDNKIFFUNK/collector/54/%2Fpeople%2FP_BDNKIFFUNK%2Fsamples%2Fvisible_to_collectors%2F54`

am I missing anything?

**Comment by masciugo** [comment]
let me add one thing:

the url used in choicesByUrl question prop is actually `http://localhost:3000/{meta_sample_url}` where _meta_sample_url_ comes from another question and it's value is `people/P_BDNKIFFUNK/samples/visible_to_collectors/54`
