### ISSUE TITLE
How to add arguments from question to custom validator?

### ISSUE THREAD

**Issue by ianubhav** [surveyjs/surveyjs#1521]
Hey can i pass some arguments from the question attributes to the custom validator. Basically I need to validate my value from a list of choices. But the custom validator has only name and value as arguments. How do I validate from the questions attributes

**Comment by dmitrykurmanov** [comment]
@ianubhav  Hello! I would suggest you to use custom function in expressions instead. Because with this approach you have access to the survey instance and to all questions and properties.

Please check the doc: https://surveyjs.io/Documentation/Library/#visibility-functions
Example: https://surveyjs.io/Examples/Library/?id=condition-customfunctions&platform=jQuery&theme=default

And here the plunker example: https://plnkr.co/edit/Hb6iKrTIO363kZAn204U?p=preview

**Comment by ianubhav** [comment]
@dmitrykurmanov How will I be able to pass choices of the question as an argument in the custom function?

**Comment by ianubhav** [comment]
Also is there a documentation on variables passed within the expression's {} parenthesis. I want to pass attributes of the question json how do I do it?

**Comment by dmitrykurmanov** [comment]
@ianubhav  if I understand you correctly  you need something like this: https://plnkr.co/edit/wQM7iOOqRDTl6TEq3igc?p=preview please check.
