### ISSUE TITLE
Answers from the starting page are removed from survey data during onComplete

### ISSUE THREAD

**Issue by schoolmeister** [surveyjs/surveyjs#1580]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When there are questions on the starting page, they are available in `survey.data` during the survey, but they are removed during the `onComplete` event. `onPartialSend` is also not called when clicking the "Start" button.

### What is the expected behavior?
I'd expect these answers to be available at the end of the survey, or to not be able to put answerable questions on the starting page at all.

### How would you reproduce the current behavior (if this is a bug)?
Here's a small plunkr: https://next.plnkr.co/edit/IjNyQdYjaSwOTo3B

### Specify your
* browser: Google Chrome
* browser version: Version 72.0.3626.121 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): happens with both vue and jquery
* surveyjs version: 1.0.73

**Comment by tsv2013** [comment]
The "strarted" page is designed to show some introductional information for the surveyee. According to the [documentation](https://surveyjs.io/Documentation/Library/?id=surveymodel#startedPage) it "The end-user could not comeback to the start page and it is not count in the progress.". Prabably it's a by design behavior do not to treat the staring page as containing answers.

If it's an ordinary survey page, could you exmplain - what do you want to achieve via setting this flag?

**Comment by schoolmeister** [comment]
I figured it was meant to be this way. But then, is it not a bug that the answers are available in `survey.data` during the survey and removed only at the end? If they're not counted in the progress I would expect them to be removed right after the starting page. 

An alternative solution would be that the person building the survey wouldn't be able to put answerable questions on the starting page in the first place, since it's slightly error prone. (I stumbled upon this because I removed my first page, forgetting that the startPage property was true. This caused the questions which were on the second page, but now on the first to not be available in my results.)

**Comment by andrewtelnov** [comment]
@schoolmeister I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@schoolmeister I have decided to fix this behavior. New unit test is added and fixed. It should work fine with new version.
As a workaround, you may set `survey.clearInvisibleValues = "none";` and it will do the trick as well. survey clears values on the start page, because the start page is invisible and by default survey clear onComplete all invsible questions.

Thank you,
Andrew
