### ISSUE TITLE
Clicking on already selected answer does not go to next page with goNextPageAutomatic

### ISSUE THREAD

**Issue by gnithin** [surveyjs/surveyjs#1584]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question or a bug. Not really sure if it's a bug.

### What is the current behavior?
- I created a survey with 2 pages (1 question per page) where all the question types are radiogroup.
- I have set `goNextPageAutomatic` to true(and allowed the next and previous buttons to be visible as well). 
- In page1, When I choose an answer (say ans1), I automatically go to the next page(page2), which is correct. 
- In page2, I click on the previous button, to go back to page1
- Now, I can only go to page2 if I select any other answer apart from ans1. Clicking on ans1, does not automatically go to the next page. Is there a way I can enable this behaviour?

### What is the expected behavior?
Clicking on an already selected answer, should automatically go to the next page with goNextPageAutomatic. It is currently not going to the next page.

### How would you reproduce the current behavior (if this is a bug)?
Here is [the example in plunker](https://plnkr.co/edit/55pUWkSZjgGKwGdB5vwL?p=preview).
- Select ans1. It automatically goes to next page.
- Click on previous.
- Select ans1 again. It does not go to the next-page, although it should.

### Specify your

* browser: firefox
* browser version: 64.0.2 (64 bit)
* surveyjs platform (angular or react or jquery or knockout or vue): Survey js react
* surveyjs version: 1.0.72

**Comment by gnithin** [comment]
Ok. Thank you for the response. Just one more question though. In the scenario that there are no navigation buttons, and ive only  enabled going to the previous question(custom navigation), not able to select the

**Comment by andrewtelnov** [comment]
@gnithin Since the data was not changed, it is hard to understand that an end-user did something and it wants to go to the next page again.

Thank you,
Andrew

**Comment by gnithin** [comment]
@andrewtelnov Ok, I'll work around this somehow. Thank you so much for your help (and your library). I'll consider this resolved and close the issue.

**Comment by dmitrykurmanov** [comment]
Thanks for sharing! Could you please describe your scenario? Does it `goNextPageAutomatic` but without navigation buttons or something else?
Maybe we missed some scenario here :)

**Comment by babgyy** [comment]
The scenario is this : 
- goNextPageAutomatic is enabled
- we do display navigation buttons 

When clicking previous to see previously answered questions, it felt weird because the only way to go forward was : 
- clicking Next again OR
- changing your answer
Doing the same thing as when answering the question initially now does nothing even though it worked the first time, it really _feels_ buggy.

I understand the argument : "the data does not change, hence goNextPageAutomatic does nothing", but in my opinion it is a bit too strict. A user interaction is a data validation. And buttons should (IMHO) behave consistently when presented multiple times, as much as possible. 

Anyway, I love surveyjs, thanks for this great lib.
