### ISSUE TITLE
Onetime survey while i save multiple drafts

### ISSUE THREAD

**Issue by vraghu1983** [surveyjs/surveyjs#176]
Hi - The plugin saves the draft of the already submitted questions in JSON format which is the expected behavior. My survey is too long - and I want a final submit button after which the survey should be non editable and still be view format only. How do i achieve this ?

**Comment by andrewtelnov** [comment]
@vraghu1983 I'am sorry, I did not get you :( Are you talking about the https://www.dxsurvey.com?

Thank you,
Andrew

**Comment by vraghu1983** [comment]
Not the service. I am just storing the json data on my local db. 
Once the submit s done I want to make the survey non editable

**Comment by vraghu1983** [comment]
Step 1.
Json data is fetched from local db. 
Survey object is instantiated and the question json will render the questions. 

Step 2: user goes on answering the data and clicks save 
Whatever json is obtained will be the answers.
This is stored back to another table in local DB

Step 3:  user opens up the survey again. He will see the ones already answered and make changes if necessary and also answer the ones which were pending and unanswered the first time. 

Step 4: completes all questions and saves. New answer json stores to locàl db. Have another button to submit the entire survey. 

Step 5: if user hit submit in step 4, and he opens the survey again, survey object instantiation n display happens , but should disable the editing of the answers. 

If still unclear will paste the code in my morning tomorrow

**Comment by andrewtelnov** [comment]
@vraghu1983 It is clear now. So you want to have a display/readonly mode in the survey.
There are several way to implement it. Do you want to see all questions in one large page or page by page? And do you want to display only answered question or unanswered as well?
Another question - relatively easy will be to set inputs into readonly or disabled mode, or do you want to render answers as text instead of inputs?
I would agree that the scenario makes the perfect sense. We just do not have this functionality yet.

Thank you,
Andrew

**Comment by vraghu1983** [comment]
I have already put the questions in various pages. And it is ok to see all questions, not just the answered ones.  It is ok to just have a readonly copy of the survey as is - not any text format.

**Comment by andrewtelnov** [comment]
@vraghu1983 How urgent do you need this functionality? I believe this functionality maybe useful for many people.
I want to introduce mode property: "edit" the default value and "display".
To make it well, it will require some time. I don't like the read only mode, since an end user may not be able to understand what is going on. Alternative rendering is a better solution IMHO.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@vraghu1983 I have decided to work on this functionality: https://github.com/andrewtelnov/surveyjs/issues/179. I just remembered, I have been asked about this functionality already and I need it for https://www.dxsurvey.com to re-run the selected results. 

Thank you,
Andrew

**Comment by vraghu1983** [comment]
Thanks.
I will manage now with disabled mode on the fly.

Thanks for considering the enhancement:)

**Comment by andrewtelnov** [comment]
@vraghu1983 Implemented under: https://github.com/andrewtelnov/surveyjs/issues/187
