### ISSUE TITLE
Chrome Bug: Failed to read the 'selectionEnd' property from 'HTMLInputElement'

### ISSUE THREAD

**Issue by Aventrue** [surveyjs/surveyjs#220]
Hello together.

When I want to submit the survey I get the error: 
```
build.js:1 Uncaught DOMException: Failed to read the 'selectionEnd' property from 'HTMLInputElement': The input element's type ('button') does not support selection.
    at i (chrome-extension://bpggmmljdiliancllaapiggllnkbjocb/content/build.js:1:29031)
    at i.showButton (chrome-extension://bpggmmljdiliancllaapiggllnkbjocb/content/build.js:2:2895)
    at chrome-extension://bpggmmljdiliancllaapiggllnkbjocb/content/build.js:2:1628
```

But that just happens with chrome explorer. I Use the Version: 55.0.2883.87 
I implement the surver tool with your angular 2 distribution. 

![image](https://cloud.githubusercontent.com/assets/17627637/22601423/1b6671aa-ea3f-11e6-921f-b736b28372df.png)

**Comment by andrewtelnov** [comment]
@Aventrue I just checked the code and find out that we do not has selectionStart or even '*selection*' in the source and compiled JavaScript.
Do you use any another library or could you try to find any code that deal with to the selectionStart attribute or a setSelectionRage method?
The google tells that somewhere in your code or in a library, you are using, there is a code that tries to get/set selection from the button html element and it fails, since the button type doesn't support selectionStart/End attributes and a setSelectionRage method.

Thank you,
Andrew
