### ISSUE TITLE
Drag/Drop not working in ASP.Net Webforms

### ISSUE THREAD

**Issue by scondra** [surveyjs/surveyjs#230]
The drag and drop capability of the questions appears to no longer work after updating to the latest version. I can still click to add the question without any issue. Here is the error stack:

Uncaught TypeError: Cannot read property 'koDragging' of null
    at DragDropHelper.exports.DragDropHelper.DragDropHelper.end (dragdrophelper.ts:48)
    at SurveyEditor.dragEnd (editor.ts:122)
    at String.dragend (eval at parseBindingsString (knockout-3.4.1.js:265), <anonymous>:3:223)
    at HTMLDivElement.<anonymous> (knockout-3.4.1.js:382)
    at HTMLDivElement.dispatch (jquery-2.1.4.min.js:7)
    at HTMLDivElement.r.handle (jquery-2.1.4.min.js:7)

**Comment by andrewtelnov** [comment]
@scondra Could you please check. Do you set the null or empty string to the editor.text? There was [an issue](https://github.com/surveyjs/editor/issues/44) reported today. I am going to work on the fix.

Thank you,
Andrew

**Comment by scondra** [comment]
@andrewtelnov The only place I'm setting the editor.text value is when I'm setting questions that were previously saved. The issue I'm having is when creating a new survey. I am unable to drag/drop any question type. I can still click on the question and it will add it.

**Comment by andrewtelnov** [comment]
@scondra I just tried it and it works fine in the current version: v0.11.1. Actually setting null/empty string or do not set nothing to editor.text lead to the same issue, that was fixed in v0.11.1.
The following line did not execute for empty survey:
`this.surveyValue["dragDropHelper"] = this.dragDropHelper; `
Here is the fix: https://github.com/surveyjs/editor/commit/8212e79c182b97364dd829606a712e9b7a8276a3

Thank you,
Andrew

**Comment by scondra** [comment]
@andrewtelnov It is now working after updating to v0.11.1. Thank you.
