### ISSUE TITLE
coefficient

### ISSUE THREAD

**Issue by xibman** [surveyjs/surveyjs#245]
Hi all,

i think it could be an insteresting feature to add a coefficient on question attributes

**Comment by andrewtelnov** [comment]
@xibman SurveyJS allows to add/remove properties on the fly. The following code will add the coefficient property, just call it before creating the Survey.

```
//add a property to the base question class and as result to all questions. 
//Property name is coefficient, type number and if the value is not set, the default value is 100.
Survey.JsonObject.metaData.addProperty("questionbase", {name: "coefficient:number", default: 100});
```
[Here is the description](http://editor.surveyjs.io/examples/addproperties.html#code) with what you can do with properites.
However, you may need it the most of this, since it is related to the SurveyJS editor mostly.

Thank you,
Andrew

**Comment by xibman** [comment]
thanks a lot for your answer !
