### ISSUE TITLE
Reordering of hidden fields after being displayed once

### ISSUE THREAD

**Issue by Ryidale** [surveyjs/surveyjs#253]
Hey,
There still appears to be an issue with the reordering of hidden fields after being displayed once ( Reported and closed   #242 ). This bug seems to affect  IE, Firefox and Chrome.

http://plnkr.co/edit/4ckw4U35EMtSjeMlmbCv?p=preview

Please see the issue please follow the instructions below with the above link:
- Select 'Application / Web' (Please note down the order of subsequent questions) and fill out the input fields
- Then change the component type to 'Database'
- Finally revert component type back to 'Application / Web' noting the previous order of questions has now been inverted.

**Comment by andrewtelnov** [comment]
@Ryidale Indeed, it is another issue. Before, it doesn't work in IE at all. Now there is an issue with reordering, I can see it.

**Comment by andrewtelnov** [comment]
@Ryidale I have found that the bug is related to [preact](https://github.com/developit/preact). We use it to get from react version jQuery and angular2 versions. The original react version works fine. pReact renders the list of elements in incorrect order. We will try to find a workaround or contact pReact team to solve the issue.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have fixed it. Before we do not render the element at all, if it is invisible. Now the div for question row is rendered always. If it is invisible, the content is empty and display is 'none'.

Thank you,
Andrew
