### ISSUE TITLE
Just wondering if there is a provision for material ui css (Feature)

### ISSUE THREAD

**Issue by svemula09** [surveyjs/surveyjs#273]
http://www.material-ui.com/#/

**Comment by andrewtelnov** [comment]
@svemula09 There are some bootstrap implementation of material design. For example: https://mdbootstrap.com/material-design-for-bootstrap/
Here is the demo of changing the css classes for elements: http://surveyjs.org/examples/jquery/survey-customcss.html

I have seen a running surveyjs on one web site with really cool material ui look.
I think we should make a demo for material design. I have added this task to our TODO list.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@svemula09 We are supporting material design now: http://surveyjs.org/examples/jquery/skin-bootstrap-material/

Thank you,
Andrew

**Comment by guilhermesad** [comment]
@andrewtelnov this link seems to be broken. We'd also want to use [Material UI](http://material-ui.com) to customize our surveys. What would be the best way to do this? Thanks!

**Comment by reginaochotzki** [comment]
We would also like to use material-ui. We want to get rid of bootstrap in our application because it doesn't get along so well with material-ui. Is there a way to replace all widgets with material-ui widgets?
By the way, I tried to register here https://surveyjs.answerdesk.io/ticket/list to create a ticket. Unfortunately, I can't register at the moment due to a server error. 
Regards Regina

**Comment by tsv2013** [comment]
Here is the bootstrap material theme on our site - https://surveyjs.io/Examples/Library?id=bootstrap-material-theme
