### ISSUE TITLE
Containers or Panels for Complex Forms

### ISSUE THREAD

**Issue by jjjeremy** [surveyjs/surveyjs#287]
Is it possible to group a set of questions into a container or panel that has its own VisibleIf setting (like pages)?  I need to be able to show or hide large groups of questions based on the result of a previous question.

I know this functionality is available for pages at the top level, but I need to do this within a page and ideally be able to nest container/panels inside others.

Thank you!

EDIT:  Indenting seems to do this visually, but it doesn't cascade the VisibleIf to the lower levels

**Comment by andrewtelnov** [comment]
@jjjeremy Will visible trigger work for you? http://surveyjs.org/examples/jquery/trigger-visible.html
You may have a list of questions/pages that will change the visibility on a value change.

Thank you,
Andrew

**Comment by jjjeremy** [comment]
Hi Andrew, thanks for the quick reply!

That would work for a static form built by me, but I'm hoping to integrate the Editor/Designer into our site so that users can build and edit their own forms.  And they'll need an intuitive way to group questions.  That's why I thought dropping questions into a panel/container would be ideal - they'd only have to set the VisibleIf on the container.

**Comment by andrewtelnov** [comment]
@jjjeremy 
Aha, the problem with this approach, we will have a new entity/definition: a group of questions. Users will have to select questions somehow to build a group. In fact there should be a list of groups of questions. It is a concepts that you have to explain to your end-users as well. I am not sure how to make it obvious for an end-user in the editor.

Visible trigger does exactly what you need, but probably not in an intuitive way.

What you probably need, if a question changes a visibility, other questions should change the visibility as well. Same with pages.

So, there should be an ability to apply visibleIf to several questions/pages, where questions maybe on different pages. This is what you need. If you are agree with this, we may discuss the UI. It is obvious how to make it in run-time and in json, unless you have something different in mind:
survey.visibility: {
  [{ name: "visibility1",
     visible: true/false,
     visibleIf: "Expression",
     questions: [the list of question names],
     pages: [the list of pages names]
  }]
}

on changing visible by set directly or by changing it based on visibleIf expression, all questions/pages will change the visible.

What do you think? I think this approach makes sense, since when the survey is large, it is hard to control all visibleIf properties in all questions/pages.

Thank you,
Andrew

**Comment by jjjeremy** [comment]
Thanks Andrew

I was thinking something more like the Panel component at http://codepen.io/travist/full/xVyMjo/  (it's under Layout Components).  You can nest panels and each panel has it's own visibility setting, just like a question, which affects everything within that panel.  Just trying to think of it from a basic user's point of view.

**Comment by andrewtelnov** [comment]
@jjjeremy Yes, I have got your idea. It makes perfect sense to me.
We've just discussed this container concepts. It looks interesting.
I think, it will be possible to implement it, without changing the json structure and all previous code should work.
There will be an another level of abstraction.
Survey->Pages->Elements and Container->Elements.
Where Elements are Containers or Questions.
So Page is a top level container. Container may have containers and questions, the number of nested containers is unlimited.

It is pretty simple to implement in run-time, as I see it. Ideally all unit tests should continue to work. However, it would require some time to implement changes in the editor.
I have added this feature in our TODO list. Could you ping me in several days? I may probably will try to implement it on this or next week-end.

The idea looks interesting to me, since if a developer do not want to see this container concepts, I will make an option to hide "Question container"/"Panel" item from the toolbox and an end-user will never see it.

PS: What additional properties, except visibile/visibleIf, do you need in Container? title, titleLocation?

Thank you,
Andrew

**Comment by jjjeremy** [comment]
@andrewtelnov 
That would be unreal!!

Additional properties:  title and titleLocation are probably all you need.  But I'll let you know if I think of something else.

Cheers,
Jeremy

**Comment by andrewtelnov** [comment]
@jjjeremy Please take a look: http://surveyjs.org/builder/

Thank you,
Andrew

**Comment by jjjeremy** [comment]
@andrewtelnov  Very cool!!!!  That works really well!

I did find an issue though.  Deleting a question from inside a panel doesn't work.  The first attempt appears to do nothing, and if you attempt to delete it again it deletes the entire panel.  Moving the question out of the panel and then deleting it does work.

Also, I suggest giving a new panel a default title (or show the name if there is no title).  It would help give the element a bit more context when a user adds a panel rather then just showing a box.  It can also be a bit difficult to drop questions into a panel so having a title makes the target less jumpy.

Otherwise, it's brilliant.  Thanks heaps!

Cheers,
Jeremy

**Comment by andrewtelnov** [comment]
@jjjeremy Yes. the bug with deleting is fixed: https://github.com/surveyjs/editor/issues/74
I am not entire happy with the drag&drop. Showing a title maybe an option. I will play with it.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@jjjeremy in the next update, in the editor, if panel title is empty, it's name will be rendered as: [name].

Thank you,
Andrew

**Comment by jjjeremy** [comment]
@andrewtelnov  
Thanks mate!
