### ISSUE TITLE
Please add new type of questions

### ISSUE THREAD

**Issue by LeXuZZ** [surveyjs/surveyjs#38]
Can you add type of question - datepicker?

**Comment by andrewtelnov** [comment]
Hi,
The feature makes perfect sense. I just do not know how to implement it well. 
It can be tricky. I do not want to create one more date picker, from one side, from another side, I do not want to depends on UI library. Plus different people may want to use different UI libraries.
Probably, I will be able to make it as a plug-in and migrate to webpack. In this case everybody will be able easily to use any UI extension.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I have created the "date" question type as a plugin example.
Please take a look: https://github.com/andrewtelnov/surveyjs/tree/master/src/plugins

**Comment by franjogordillo** [comment]
Hi Andrew can you please tell me in which file can i find the questions , i want to delete a few questions.

**Comment by andrewtelnov** [comment]
@franjogordillo Do you want to delete question(s) from the survey js editor? Or do you want to make a library size smaller?

**Comment by franjogordillo** [comment]
Yes Andrew remove some questions from de GUI part of survey editor , for example remove the matrix multiple rows.

**Comment by andrewtelnov** [comment]
@franjogordillo You may use the options.questionTypes array to limit the number of question the editor support, https://github.com/andrewtelnov/surveyjs.editor/issues/4 
I am sorry about lack of demos for Editor. I am working on the Editor web site and examples right now.

Thank you,
Andrew

**Comment by tsv2013** [comment]
@LeXuZZ, @franjogordillo Since v0.12.0 we can use 3rd party controls as editors for questions. We've implamented a couple - [jqueryui](https://jqueryui.com/datepicker/) [datepicker](http://surveyjs.org/examples/jquery/custom-widget-datepicker.html) and [devextreme](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxTagBox/) [dxTagBox](http://surveyjs.org/examples/jquery/custom-widget-tagbox.html).

@andrewtelnov @dmitrykurmanov We can discuss creation of some type of repository to contribute such widgets to. The place where contributors can share their widgets and experience.
