### ISSUE TITLE
Custom Widgets not rendered when viewing the survey.

### ISSUE THREAD

**Issue by muhfred** [surveyjs/surveyjs#395]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

I created a survey with editor and saved the json to a database, when viewing the survey, custom widgets are not rendered. Does it have anything to do with being the json editor changed from "questions" to "elements" ? example used is barrating widget.

### What is the expected behavior?

I expect that custom widgets are rendered when viewing the survey.

### How would you reproduce the current behavior (if this is a bug)?
If I got the json like this with "elements" instead of questions, the custom widget will not be rendered as expected.
`var survey = new Survey.Model({ elements: [
 { type: "dropdown", name: "barrating1", renderAs: "barrating", "ratingTheme": "fontawesome-stars", title: "Please rate the moive you've just watched", 
     choices: ["1", "2", "3", "4", "5"] }
]});`

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: chrome
* browser version: 58.x
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 0.12.15

**Comment by tsv2013** [comment]
I've managed to reproduce the following behaviour:

With the
`{ elements: [ { type: "dropdown", name: "barrating1", renderAs: "barrating", "ratingTheme": "fontawesome-stars", title: "Please rate the moive you've just watched", choices: ["1", "2", "3", "4", "5"] } ]}`
json I've got the "`There is no visible page or question in the survey.`" message instead of question.

With the
`{ questions: [ { type: "dropdown", name: "barrating1", renderAs: "barrating", "ratingTheme": "fontawesome-stars", title: "Please rate the moive you've just watched", choices: ["1", "2", "3", "4", "5"] } ]}`
json everething works like a charm.

@muhfred Can you confirm the same behaviour on your side? Or you have another issue(s)?

**Comment by muhfred** [comment]
all questions are shown except for the custom widget.

**Comment by tsv2013** [comment]
@muhfred I've fixed issue related to the "elements" root property (fix will be available in the nearest update) and created a plunk with current dev version of survey-jquery package: https://plnkr.co/edit/tj0BfVzVkC8MidOfgjtm?p=preview
All questions are displayed correct for me.
Please feel free to modify the plunk to reproduce issue if it still not fixed.

**Comment by muhfred** [comment]
awesome, thank you, please tell which branch I should use for pull requests, I finished a localization file for arabic.
Thanks.

**Comment by andrewtelnov** [comment]
@muhfred It should be the master, https://github.com/surveyjs/surveyjs/tree/master/src/localization

Thank you,
Andrew

**Comment by muhfred** [comment]
Is the issue has been fixed in version 0.12.17? I'm just checking to make sure.

**Comment by andrewtelnov** [comment]
@muhfred Sure, the fixes are in the latest released version.

Thank you,
Andrew
