### ISSUE TITLE
Is there a possibility to set CSS classes to a single question?

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#396]
now i see that in model.defaultBootstrapCss there is an object that contains the main css classes, and work for all questions...

In my survey, i need to specify a particular css class only for one o two specific question, are there any possibility to do it adding an attribute in json string when a compose the survey's json?

Thanks very much ;)

**Comment by andrewtelnov** [comment]
@care46 We do not have this functionality yet, but it has been discussed and it is in our TODO list.
Right now on rendering questions are using the surveyCss object directly. The idea is to have a function that will create an object with all required css classes from surveyCss object, call an event and rendering code will use this css object, instead of global surveyCss.
It will give you an ability to modify the default css class for a particular question/panel/page objects.

Thank you,
Andrew

**Comment by care46** [comment]
ook!
