### ISSUE TITLE
Add "startWithNewLine" option to each element in Matrix (dynamic rows)

### ISSUE THREAD

**Issue by knightsouldier** [surveyjs/surveyjs#458]
### Are you requesting a feature, reporting a bug or ask a question?
Feature

### What is the current behavior?
Continuous horizontal display of elements in Matrix (dynamic rows)

### What is the expected behavior?
Each element should have the "startWithNewLine" option to prevent excessively wide sections.

**Comment by Kuhax** [comment]
I would like to see this feature implemented as well.

**Comment by andrewtelnov** [comment]
@knightsouldier @Kuhax Guys, I am sorry, but I did not get you :( Could describe what you are trying to achieve?
Do you want to divide the matrix? What is the problem you are trying to solve, so we can work on the solution.

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov I'm using matrixdynamic a lot, that's why I have raised many questions about it. @knightsouldier is right; in matrixdynamic rows tend to be very wide if you introduce too many columns. The feature we are interested in is to be able to mark certain columns with `startWithNewLine` (or similar). This way when you add new row it will allow to show you the contents both height-wise and widh-wise.

Let me explain it graphically:

This matrixdynamic contains only one row in both examples

- `startWithNewLine` for a row 

<table>
<tr>
<td><b>Column_1</b></td>
<td><b>Column_2</b></td>
<td><b>Column_3</b></td>
<td><b>Column_4</b></td>
</tr>
<tr>
<td>Row 1 Col 1</td>
<td>Row 1 Col 2</td>
<td>Row 1 Col 3</td>
<td>Row 1 Col 4</td>
</tr>
</table>   

- `startWithNewLine` for a column (in this case 2nd column was marked as `startWithNewLine`)

<table>
<tr>
<td><b>Column_1</b></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Row 1 Col 1</td>
<td></td>
<td></td>
</tr>
<tr>
<td><b>Column_2</b></td>
<td><b>Column_3</b></td>
<td><b>Column_4</b></td>
</tr>
<tr>
<td>Row 1 Col 2</td>
<td>Row 1 Col 3</td>
<td>Row 1 Col 4</td>
</tr>
</table> 

This way you may add more columns in the matrixdynamic without messing up with custom css or custom width values for columns.

Hopefully I've explained myself well and @knightsouldier agrees with this.

**Comment by andrewtelnov** [comment]
@Kuhax Yes, I got it. So basically, you want to have several html tables row by one matrix row.
In this case you would have to repeat the header every time or the end-user will not understand what is going on or it should be something more complex, IMHO.

Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov  currently I have several multimatrix with 10-15 columns. So I'm looking for a way to make it look good. One way is to implement a huge horizontal scroll (which is not ideal). Another way may be `startWithNewLine` for columns. 

It's true that `startWithNewLine` for columns is less intuitive for end user and one way to solve it is to repeat a column name for each row. In my opinion a way to overcome it is to use placeholders to indicate end-user what is what and to group common columns vertically.

**Comment by andrewtelnov** [comment]
@Kuhax To be honest, I do not like the idea with startWithNewLine. It looks like a quick dirty solution for the issue you have guys. I personally would not use it in my survey, since it generates other usability issues.
The good solution to have something like: https://documentation.devexpress.com/#WindowsForms/CustomDocument3468

**Comment by Kuhax** [comment]
@andrewtelnov I agree that startWithNewLine on columns is a dirty hack. It may be confusing for the end user and even be pretty ugly.  Certainly banded GridView looks way better and it will get the job done, but it looks that a lot of custom code (for both logic and presentation) should be added as well.

In my particular case I have a few matrixdynamic with way too many columns (I can't do anything about the contents, they just should be there). The result is that the whole row looks compressed and unreadable on any screen. Since I have a mix of editors (select2, textboxes, dropdowns) all of them seem to adjust themselves as they wish. 

Is there any way for them to adjust to their maximum width (for dropdowns, at least)? I mean if a dropdown has a list, it should resize itself to the length of the longest option.  I'll try to tinker with horizontalScroll and width properties (I don't mind showing huge horizontal scroll, if needed)

Any advice?

Thanks in advance

**Comment by andrewtelnov** [comment]
@Kuhax It will be possible to set max-width for the most elements, except dropdown. Select element doesn't look at max-width style. Here is the explanation: https://stackoverflow.com/questions/10672586/how-to-make-select-elements-shrink-to-max-width-percent-style-within-fieldset
I may add maxWidth property to the column of course. We have minWidth property already. However, I am not sure it will help you :-(


Thank you,
Andrew

**Comment by Kuhax** [comment]
@andrewtelnov I have added `"horizontalScroll": true,` which helps somehow but `"columnMinWidth": "whatever"` doesn't seem to have any effect. Adding `style='width: 90%;'` to Select2tagbox `htmlTemplate` has no effect either.

Actually looks like the width of the column is being dictated by the width of the column name.

Is there any other way to make columns wider ?

**Comment by andrewtelnov** [comment]
@Kuhax https://plnkr.co/edit/K5eLaxL4XWu1MrqqGU2c?p=preview
In this example, I have set the minWidth to 300px for the second column and it works fine.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
No reply for several months. I am closing the issue.
