### ISSUE TITLE
Add display mode to page

### ISSUE THREAD

**Issue by rogereriksen** [surveyjs/surveyjs#485]
### Are you requesting a feature, reporting a bug or ask a question?

Requesting a feature.

### What is the current behavior?

Cannot set mode to "display" on page.

### What is the expected behavior?

Be able to control mode at page level.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by andrewtelnov** [comment]
@rogereriksen Could you please describe your scenario, why do you need this functionality?
There is already question.readOnly : boolean (default false) property. You may set it to a question. Why do you need it on the page level? 

Thank you,
Andrew

**Comment by rogereriksen** [comment]
Planning to set up a solution where I can have case manager/agent read all responses with view only on first pages and then do some kind of management/evaluation on pages only visible to that role.

**Comment by andrewtelnov** [comment]
@rogereriksen Ok, I have just added it into our TODO list. 
Unfortunately, it is not as easy as it seems. There is a Panel/Page concepts. So the readOnly should be on the Panel level as well. Additionally, at the current moment Question doesn't know about Panel or Page it belongs to. It has to be introduced as well.
I mean, it may take some time since we are busy with some other tasks at the current moment. But eventually, we will introduce this functionality.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@rogereriksen It has been implemented. Here is [the example](https://surveyjs.io/Examples/Library/?id=survey-displaymode&platform)

Thank you,
Andrew
