### ISSUE TITLE
Link to Database

### ISSUE THREAD

**Issue by Hafees89** [surveyjs/surveyjs#524]
Hi,

Any how I can save my data directly to SQL Server? Maybe there is source code I can refer to?

Thank you.

**Comment by andrewtelnov** [comment]
@Hafees89 It depends on your server platform. We have in our plans to create tutorials/examples for the most popular platform, but it is not in the high priority TODO list.
You may easily find the answer on stackoverflow.com: How to save JSON in my SQL Server [php/asp.net/...]

Thank you,
Andrew

**Comment by Hafees89** [comment]
Which file I need to alter so I can save JSON into SQL Server? It is at survey.onComplete.add(function(result) { or there is other way I could do it? Mind to guide me on this? I really stuck on this.. Need this kinda urgently.. 

Thank you.

**Comment by andrewtelnov** [comment]
@Hafees89 Again, you did not mention your server platform.
Here is our code. 
On the client side:
https://github.com/surveyjs/surveyjs/blob/master/src/dxSurveyService.ts take a look on sendResult. It calls on completing survey. You may call it on onComplete event.
postId - Guid for the survey, so all results for the same survey will be in the same file/table
result - survey.data
onSendResult - callback function that calls on completing the ajax request.

On the server asp.net mvc:
```
    /// <summary>
    /// Use it for sending the survey result to the dxSurvey service.
    /// </summary>
    public class SurveyClientPostResult {
        /// <summary>
        /// The Post Id of your survey.
        /// </summary>
        public Guid PostId { get; set; }
        /// <summary>
        /// Your survey result as Json string.
        /// </summary>
        public string SurveyResult { get; set; }
        /// <summary>
        /// Optional. The unique client id for a person running the survey.
        /// </summary>
        public string ClientId { get; set; }
        /// <summary>
        /// Optional. Valid if CliendId is not empty. True if a person doesn't complete the survey yet.
        /// </summary>
        public bool IsPartialCompleted { get; set; }
    }
        [ActionName("post")]
        public IHttpActionResult Post([FromBody]SurveyClientPostResult result) {
            if (result == null || string.IsNullOrEmpty(result.SurveyResult)) return BadRequest();
            if(!new SurveyControllerImpl().PostResult(result.PostId, result.SurveyResult, result.ClientId, result.IsPartialCompleted)) {
                return BadRequest("Check parameters values.");
            }
            return Ok();
        }

```
Again, there a lot of examples of implementing this task on stackoverflow.com and other resources. 
To be honest, surveyjs library has nothing to do with this part, since the code and approaches may be very different and depends on server platform and your goals.

Thank you,
Andrew

**Comment by Hafees89** [comment]
Sorry @andrewtelnov for making this trouble for you. I'm using SQL Server 2014. Thank you again for helping me out. I'm glad using this as reference. Thank you so much.
