### ISSUE TITLE
Question: A way to run analytics on responses

### ISSUE THREAD

**Issue by prasadh13** [surveyjs/surveyjs#542]
### Are you requesting a feature, reporting a bug or ask a question?
Question : Is there a way to do analysis on the surveys? For example, I want to download the responses of the survey and run analytics on it. So I would like a questions to be the columns and answers by the users to be the row. Any thoughts on how to proceed? I am working with MEAN stack.

### Specify your

* browser: chrome
* browser version: 60.0.3112.90
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version:

**Comment by dmitrykurmanov** [comment]
@prasadh13 hello! I think that I did not fully understand you. You can process survey results as you like because it is just JSON. Or you may try https://dxsurvey.com/ , pleasse see an example: http://surveyjs.org/examples/angular/service-result/ (after complete survey please wait a minute to see diagram)

**Comment by andrewtelnov** [comment]
No reply for a long time. I am closing the issue.
