### ISSUE TITLE
SurveyJs designer running in local server

### ISSUE THREAD

**Issue by h123eranga** [surveyjs/surveyjs#564]
Is there are way to use survey designer of surveyjs in local server? Using node server?

**Comment by andrewtelnov** [comment]
@h123eranga 
Of course, you may use SurveyJS Editor in your web application.However, please note that you will need a commercial license to use it in your project(s).
Node Server is a valid options, since SurveyJS Editor is a common JavaScript library. Here is the example of running SurveyJS Editor in plunker: https://plnkr.co/edit/yJ4g337Vmk8HXZ4AksBi?p=preview

Here is the instruction to insert SurveyJS Editor into your project: http://editor.surveyjs.io/
There are links on repos for different platforms that may help you to start.
Here is the link on license description: http://editor.surveyjs.io/license.html

Thank you,
Andrew

**Comment by h123eranga** [comment]
Thanks and I can use it but I can't use it in projects. I am generating only the JSON object. Why is that?

**Comment by andrewtelnov** [comment]
@h123eranga Sorry, I do not understand you.
If you want to let your users/customers to create their own surveys, you will likely need the Editor on your website/web application.
If you want to show your users/customers only your predefined survey, then you likely do not need the Editor and you may use this link, for example http://surveyjs.org/builder to create Survey JSON. It is free.

Thank you,
Andrew

**Comment by h123eranga** [comment]
I am expecting to use the survey builder. I need to run it on my local machine

**Comment by dmitrykurmanov** [comment]
@h123eranga, hello! We have https://github.com/surveyjs/editor repo. It is source code.

**Comment by h123eranga** [comment]
And, is it free to use your site source? Can I use the builder there?

**Comment by dmitrykurmanov** [comment]
@h123eranga, we have publick repo of site https://github.com/surveyjs/site under the MIT license

**Comment by h123eranga** [comment]
Can we select a specific elements in the JSON array using js or any other technology.

**Comment by h123eranga** [comment]
Anyway, Thank you very much for responding quickly for our matters you bot @andrewtelnov and @dmitrykurmanov .
