### ISSUE TITLE
Select2 widget looses focus when option is selected

### ISSUE THREAD

**Issue by nikitakarpenkov** [surveyjs/surveyjs#653]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Select2 widget looses focus when option is selected. So on next tab press the first element on the page gets focus.

### What is the expected behavior?

Focus has to persist on the same question when option is selected. Next tab press has to move focus to the next question.

#### Workaround

Add the following line to the widget afterRender callback:

```
$el.on('select2:select', function (e) {
     question.value = e.target.value;
     e.target.focus(); // add this line to keep the focus
});

```

See the result here: https://plnkr.co/edit/dFI1NYNCdKgEeboJKp7B

### Specify your

* browser: Google Chrome
* browser version: 60.0.3112.113 (Official Build) (64-bit)
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 0.12.25

**Comment by dmitrykurmanov** [comment]
@nikitakarpenkov, hello! Thanks for finding the bug. After some time I've found a reason. It is bug in select2 which was fixed in 4.0.4 version, please see https://github.com/select2/select2/releases/tag/4.0.4

Updated example: https://plnkr.co/edit/YZcrKRNJo8pfMHtAgF7J?p=preview
just changed 4.0.3 to 4.0.4 for select2

and I will update the site example
