### ISSUE TITLE
Optional skip button

### ISSUE THREAD

**Issue by camloken** [surveyjs/surveyjs#713]
It would be nice if you could add a skip button at the bottom of the survey that would allow users to opt out of the survey if they don't want to take it.  You could even customize the behaviour to "Never show again" or "Show next time" and "Repeat x.number of times".

**Comment by andrewtelnov** [comment]
@camloken Are you talking about a survey integrated into a web page/application?
SurveyJS Library is just a JavaScript widget. You may show/hide it as you want based on your business logic. SurveyJS Library doesn't have access to web application sessions, user accounts and so on. Every platform has its own implementation.
I am sure, there are a lot of examples how do implement this functionality for a specific platform and it should not be hard to code, since it is a basic thing.

Thank you,
Andrew

**Comment by camloken** [comment]
Yes, you are correct. There are many different (hacky) ways to do this. I guess what I'm really asking for is a way to create custom buttons in the .sv_nav at the bottom of the survey. You could add an id or a callback that would allow developers to tie logic into it (for example a skip button). It's difficult, in React, to inject elements outside of their virtual dom. So having a way to create a custom button would make this a lot easier.

**Comment by andrewtelnov** [comment]
@camloken You may render navigation buttons by yourself and make the built-in navigation buttons are invisible,` survey.showNavigationButtons = false;`.
Here is [the demo](https://surveyjs.io/Examples/Library/?id=survey-customnavigation&platform=Reactjs)

Thank you,
Andrew

**Comment by camloken** [comment]
Thanks, I didn't realize you could do this.
