### ISSUE TITLE
widget in matrixdynamic

### ISSUE THREAD

**Issue by care46** [surveyjs/surveyjs#739]
hi, i have added a custom widget in matrixdynamic to have a different view and function in one column of the table..

My case is:
- matrixdynamic with only one column drawn by a custom widget based on a text type question

My problem is this:
- if i have 2 row in table, and i remove the second row, when i am in willUnmount widget function, the property question.id, question.value ecc  is relative to the line that i have deleted, but if i have 2 row and i remove the first, when i am in willUnmount widget function, the property question.id, question.value ecc  is relative to the second row (that remain in table) and isn't relative to the row that i have remove

It's a bug or i have to change something?

thank you

**Comment by andrewtelnov** [comment]
@care46 Could you please provide us with an example?

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov  ok i made an example in plunker

https://plnkr.co/edit/mwsipOEupQnGPcR00vAD?p=preview

I have set a custom widget, and in willunmount function i put an alert of question.value

If you put a value in first row and a different value in second row, then you remove the first row, you will see that the alert return the value of the row that remain in table and not the value that you remove

thank you!

**Comment by andrewtelnov** [comment]
@care46 Yes, I got the issue now. It looks like a bug to me. I will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@care46 I have fixed the issue. matrix dynamic row use incorrect key. 

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov if i try with my plunker example, it will be ok?

**Comment by andrewtelnov** [comment]
@care46 I have just tried it: https://plnkr.co/edit/RiGlwBcOAOBKIhnzC1iQ?p=preview
and it doesn't delete the correct rows :((( 
Let me go back to the issue...

**Comment by andrewtelnov** [comment]
@care46 Arh, I see the reason: https://github.com/surveyjs/surveyjs/commits/master
The release was made before I have fixed the bug. It works fine locally, but not in the release version.
We will do the next release on this week. I may prepare the dev version if you need the fix ASAP.

Thank you,
Andrew

**Comment by care46** [comment]
@andrewtelnov ok perfect, i can wait the next version! ;)

**Comment by care46** [comment]
@andrewtelnov  I have another question, the willonmount function will be called when I remove a row from a table, or when the question is hidden under condition, but it is also called when page change in the survey.. there is an option to locate when they are in the case of a "change page" and not in "hidden" case?

**Comment by tsv2013** [comment]
@care46 If we'll take a look into the [custom-widget.tsx](https://github.com/surveyjs/surveyjs/blob/master/src/react/custom-widget.tsx) file, the `render` function is look like
```
    render(): JSX.Element {
        if (!this.questionBase || !this.creator) { return null; }
        if (!this.questionBase.visible) { return null; }
/// ... other code
```
If question is invisible, it is not rendered. Similar code is written in the `matrixdynamic` cell renderer.

So in both cases (row removal/question hiding) element will not be rendered and should be removed from DOM.
According to the [react.component documentation](https://reactjs.org/docs/react-component.html#unmounting)

> This method is called when a component is being removed from the DOM
> componentWillUnmount()

Thus in any case the `willUnmount` method of the custom widget will be called.

Due to the elements rendering is controlled by the react/preact engine there is no built-in way to know - what caused this re-rendering. And there are no means to get unmount cause.

Probably this could be obtained on the survey logic level, if we will process question [visibility change notifications](https://surveyjs.io/Documentation/Library/?id=surveymodel#onVisibleChanged).

**Comment by care46** [comment]
@andrewtelnov i see that the version was updated at 0.12.36, but if i try with plunker example, the bug was the same... maybe the fix is not in 0.12.36 but will be in 0.12.37?

thank you

**Comment by care46** [comment]
@andrewtelnov sorry, i have js in cache, it seems to be ok... now i try!

**Comment by care46** [comment]
IT'S OK!!!
