### ISSUE TITLE
SurveyJS for Angular really slow with relatively large json model

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/surveyjs#922]
### Are you requesting a feature, reporting a bug or ask a question?

Bug / performance issue.

### What is the current behavior?

SurveyJS is really slow in an Angular 5.2 + TypeScript 2.6 setup with a relatively large json model.

### What is the expected behavior?

Performance should be much better as we  are using same json model in an Aurelia + jQuery setup without this slowness.

### How would you reproduce the current behavior (if this is a bug)?

Zip attached in following issue: https://github.com/surveyjs/widgets/issues/34

I thought it was related to widgets projects, but it's still that slow when all widget stuff is commented out.

Just run the app and toggle the radio buttons of the first question - the more you toggle them the slower the rest of the questions refresh.

[EDIT]: Turns out same json model is just as slow in SurveyJS Editor, so probably not related to Angular per se. 

### Specify your

* browser: Chrome
* browser version: 63
* surveyjs platform (angular or react or jquery or knockout or vue): angular cli
* surveyjs version: 1.0.8

**Comment by dmitrykurmanov** [comment]
We've fixed the bug, fix will available in the next patch release. Thank you!

**Comment by halexiev-hedgeserv** [comment]
@dmitrykurmanov Thank you - bug is fixed in 1.0.9.

**Comment by albertoVieiraNeto** [comment]
i'm using surveyjs creator inside a angular 7 template (apex angular) and for some reason the component seems very slow,  and throws several reflows warnings, i dont have this issue for example when using components like devextreme. does anyone have a tip on how to improve performance?

**Comment by andrewtelnov** [comment]
@albertoVieiraNeto Do you have the same issue with our Angular CLI example? Here is the [repo](https://github.com/surveyjs/surveyjs_angular_cli)
We have SurveyJS Librar and Creator for Angular 7 on CodeSandBox [example](https://codesandbox.io/s/30k3n351mm).

Thank you,
Andrew

**Comment by MartinLichtblau** [comment]
Including the same survey with five questions on angular page ~10 times takes forever. The whole page becomes unresponsive for 10 seconds. 
Is there a way to speed it up? IMO rendering time / performance should be a priority. No one likes waiting and it's know that it can influence people.

**Comment by tsv2013** [comment]
@MartinLichtblau What version of survey-angular are you using? If you are using the latest version (1.1.20) then provide us with a sample illustrating the issue.

**Comment by MartinLichtblau** [comment]
@tsv2013 I am using version 1.1.17 and cannot install 1.1.20 because of #1903. 

I run this code:
```
    runAllSurveys() {
        const surveyJSON = {surveyId: 'b9255fe5-ab89-4619-86ec-197e97da646b'};
        Survey.StylesManager.applyTheme("bootstrap");
        this.qaItems.forEach((result: any, index: number) => {
            let survey = new Survey.Model(surveyJSON);
            survey.showNavigationButtons = false;
            survey.showCompletedPage = false;
            this.surveys.push(survey);
            Survey.SurveyNG.render('surveyElement'+index, {model: survey});
        });
    }
```

Get this console output in chrome when loading the same survey six times:
```
[Violation] 'load' handler took <N>ms
19:17:55.686 zone.js:416 [Violation] 'load' handler took 285ms
19:17:58.061 zone.js:416 [Violation] 'load' handler took 1170ms
19:17:59.475 zone.js:416 [Violation] 'load' handler took 1401ms
19:18:01.012 zone.js:416 [Violation] 'load' handler took 1528ms
19:18:02.597 zone.js:416 [Violation] 'load' handler took 1577ms
19:18:04.159 zone.js:416 [Violation] 'load' handler took 1553ms
19:18:05.747 zone.js:416 [Violation] 'load' handler took 1579ms
```

If I remove parts of the survey it loads faster. But it's only 6 elements, so it shouldn't take so long. 
That's the survey:
```
{
 title: "Answer Assessment Questionnaire",
 pages: [
  {
   name: "page1",
   elements: [
    {
     type: "rating",
     name: "aaq_overall_rating",
     title: "Answer Rating",
     description: "1=Extremely BAD,  9=Extremely GOOD",
     isRequired: true,
     requiredIf: "{aaq_completeness} notempty or {aaq_comprehensibility} notempty or {aaq_concision} notempty",
     rateMax: 9
    },
    {
     type: "rating",
     name: "aaq_comprehensibility",
     title: "How easy is it to understand?",
     description: "1=Extremely HARD,   7=Extremely EASY",
     isRequired: true,
     rateMax: 7
    },
    {
     type: "rating",
     name: "aaq_concision",
     title: "How much of it is task-unrelated?",
     isRequired: true,
     rateValues: [
      {
       value: "1",
       text: "0%"
      },
      {
       value: "2",
       text: "25%"
      },
      {
       value: "3",
       text: "50%"
      },
      {
       value: "4",
       text: "75%"
      },
      {
       value: "5",
       text: "100%"
      }
     ],
     rateMax: 7
    },
    {
     type: "rating",
     name: "aaq_completeness",
     title: "To what degree does it answer the task?",
     isRequired: true,
     rateValues: [
      {
       value: "1",
       text: "0%"
      },
      {
       value: "2",
       text: "25%"
      },
      {
       value: "3",
       text: "50%"
      },
      {
       value: "4",
       text: "75%"
      },
      {
       value: "5",
       text: "100%"
      }
     ],
     rateMax: 7
    },
    {
     type: "rating",
     name: "aaq_accuracy",
     title: "How accurately does it match the task?",
     description: "1=Extremely GENERAL, 7=Extremely SPECIFIC",
     isRequired: true,
     rateMax: 7
    },
    {
     type: "rating",
     name: "aaq_confidence",
     title: "How confident are you in the answer?",
     description: "-3=Certain it's WRONG, 0=UNCERTAIN, +3=Certain it's RIGHT",
     isRequired: true,
     rateValues: [
      {
       value: "1",
       text: "-3"
      },
      {
       value: "2",
       text: "-2"
      },
      {
       value: "3",
       text: "-1"
      },
      {
       value: "4",
       text: "0"
      },
      {
       value: "5",
       text: "+1"
      },
      {
       value: "6",
       text: "+2"
      },
      {
       value: "7",
       text: "+3"
      }
     ],
     rateMax: 7
    }
   ]
  }
 ],
 showTitle: false,
 showPageTitles: false,
 showCompletedPage: false,
 showQuestionNumbers: "off"
}
```

**Comment by tsv2013** [comment]
@MartinLichtblau I've checked your JSON in our boilerplate sample repo - https://github.com/surveyjs/surveyjs_angular_cli - and haven't managed to reproduce it

I've tested both JSON you provided and link to surveyId in our storage.
The longest time (about 300ms) was for the `{surveyId: 'b9255fe5-ab89-4619-86ec-197e97da646b'}` JSON because this configuration gets survey JSON from our server via HTTP request.

Could you provide us with a sample project to investigate this performance issue?

**Comment by MartinLichtblau** [comment]
I found the culprits! Chrome extensions. Namely [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) and [Right Click Opens Link New Tab Correct Order](https://chrome.google.com/webstore/detail/right-click-opens-link-ne/mhjkeimpgjokbjmioglhlngefbddppnn). They increase processing time by 100% and increase even more with every survey. I guess they use MutationObserver to detect DOM changes which are massively triggered because surveyjs renders many times (for every question?) and additionally it gets worse because they seems to build and thus don't behave linearly. 

Anyway, my issue is solved. Sorry for bothering you. But perhaps this will come up another time. So Thank you for your effort and surveyjs!
