### ISSUE TITLE
Customize editor and questions - putting angular content inside custom question

### ISSUE THREAD

**Issue by rangasurendra** [surveyjs/surveyjs#924]
### Are you requesting a feature, reporting a bug or ask a question?

Hi,
I followed [this link](https://github.com/surveyjs/surveyjs_angular_quickstart/tree/editor-customizations) editor-customization branch example and create a custom question control. 

I ran in to a requirement of showing angular content inside the htmlTemplate section shown below,

Just wanted to know whether this is supported, or I have to simple deal with HTML and JS 

Thanks !
Ranga
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
import * as Survey from "survey-angular";
import * as SurveyAngular from "survey-angular";

export let peopleWidget: any = {
  name: "people",
  isFit: function (question: Survey.QuestionBase): boolean {
    return question["renderAs"] === "people";
  },
  htmlTemplate:
  `<div class=".people-container" style="width: 500px; height: 200px;"> 
    This is people picker
    <input type="button" (click)="alert('test');" />
    <button mat-button>Click me!</button>
  </div>`,
  afterRender: (question: Survey.QuestionBase, el: HTMLElement): void => {
    console.log(question);
    console.log(el); // here el is the 'htmlTemplate' supplied above
  }
};

SurveyAngular.JsonObject.metaData.addProperty("text", { name: "renderAs", default: "standard", choices: ["standard", "non-standard"] });
SurveyAngular.CustomWidgetCollection.Instance.addCustomWidget(peopleWidget);


```

### Specify your

* browser:
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
SurveyJS custom widgets have framework-independent code. Content of the `htmlTemplate` property is rendered into DOM as is. After that you can process it any available way in the `afterRender` function. 

That's why Angular bindings will not work for the markup inside the `htmlTemplate` property.

You can see custom widgets examples in the https://github.com/surveyjs/widgets repository. Sample usage of the custom widgets is demonstrated in this repo - https://github.com/surveyjs/surveyjs_angular_cli
