### ISSUE TITLE
Bug: onComplete firing before onCurrentPageChanged with 'complete survey' trigger

### ISSUE THREAD

**Issue by fastclemmy** [surveyjs/surveyjs#963]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When using the 'Complete survey' trigger on a question, the onComplete event is fired before the onCurrentPageChanged one.

### What is the expected behavior?

The correct order should be first onCurrentPageChanged then onComplete .

### How would you reproduce the current behavior (if this is a bug)?

See above.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://codepen.io/fastclemmy/pen/wyNwOE

### Specify your

* browser: Firefox
* browser version: 58.0.2
* surveyjs platform (angular or react or jquery or knockout or vue): jQuery
* surveyjs version: 1.0.11

**Comment by andrewtelnov** [comment]
@fastclemmy I have fixed it, by adding a new unit test and fixed it.
However, I'm not sure you will like the solution. Because onCurrentPageChanged doesn't call at all in this case. In fact the page is not changed, the survey state is changed from "running" to "completed".
You may look at my fix. What do you think?

Thank you,
Andrew

**Comment by fastclemmy** [comment]
Sounds good to me, thanks you!
